export default {
  CHARGE_BACK: 'CHARGE_BACK',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  PURCHASE: 'PURCHASE',
  REFUND: 'REFUND',
  REQUEST_INITIAL: 'REQUEST_INITIAL',
  REQUEST_RECUR: 'REQUEST_RECUR',
  SIGNUP: 'SIGNUP',
  SUBSCRIPTION: 'SUBSCRIPTION',
  SUBSCRIPTION_RECUR: 'SUBSCRIPTION_RECUR',
  SUBSCRIPTION_CANCEL: 'CANCEL_SUBSCRIPTION',
};

